/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  Controllers
 *  model: modified-Jiwy-1
 *  expmt: modified-Jiwy-1
 *  date:  June 8, 2026
 *  time:  4:41:00 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxinteg.h"
#include "xxfuncs.h"
#include "xxsubmod.h"

/* The submodel I/O variables */
XXInteger xx_number_of_inputs = 4;
XXInteger xx_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_names[] = {
	"pitch_current_position",
	"pitch_target_position",
	"yaw_current_position",
	"yaw_target_position"
,	NULL
};
XXString xx_output_names[] = {
	"pitch_out",
	"yaw_out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void XXCopyInputsToVariables (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	xx_V[13] = u[0];		/* pitch_current_position */
	xx_V[14] = u[1];		/* pitch_target_position */
	xx_V[17] = u[2];		/* yaw_current_position */
	xx_V[18] = u[3];		/* yaw_target_position */

}

/* This function uses the output variables to fill the output vector */
void XXCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	xx_V[16];		/* pitch_out */
	y[1] = 	xx_V[15];		/* yaw_out */

}

/* The initialization function for submodel */
void XXInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	xx_initialize = XXTRUE;
	xx_steps = 0;
	XXModelInitialize ();
	XXDiscreteInitialize ();

	/* Copy the inputs */
	xx_time = t;
	XXCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	XXCalculateInitial ();
	XXCalculateStatic ();
	XXCalculateInput ();
	XXCalculateDynamic ();
	XXCalculateOutput ();

	/* Set the outputs */
	XXCopyVariablesToOutputs (y);

	/* End of initialization phase */
	xx_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void XXCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	xx_time = t;
	XXCopyInputsToVariables (u);

	/* Calculate the model */
	XXCalculateInput ();
	XXDiscreteStep ();
	XXCalculateOutput ();

	/* Copy the outputs */
	XXCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void XXTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	xx_time = t;
	XXCopyInputsToVariables (u);

	/* Calculate the final model equations */
	XXCalculateFinal ();

	/* Set the outputs */
	XXCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	XXModelTerminate ();
	XXDiscreteTerminate ();
}

