/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinverse.c
 *  subm:  Controllers
 *  model: modified-Jiwy-1
 *  expmt: modified-Jiwy-1
 *  date:  June 8, 2026
 *  time:  4:41:00 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* No matrix support functions are needed for this model */

