/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.c
 *  model: modified-Jiwy-1
 *  expmt: modified-Jiwy-1
 *  date:  June 8, 2026
 *  time:  4:41:00 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "xxmodel.h"
#include "xxfuncs.h"

/* the global variables */
XXDouble xx_start_time = 0.0;
XXDouble xx_finish_time = 20.0;
XXDouble xx_step_size = 0.001;
XXDouble xx_time = 0.0;
XXInteger xx_steps = 0;
XXBoolean xx_initialize = XXTRUE;
XXBoolean xx_major = XXTRUE;
XXBoolean xx_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble xx_P[xx_parameters_size];		/* parameters */
XXDouble xx_I[xx_initialvalues_size];		/* initial values */
XXDouble xx_V[xx_variables_size];		/* variables */
XXDouble xx_s[xx_states_size];		/* states */
XXDouble xx_R[xx_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXString xx_parameter_names[] = {
	"PositionControllerPan\\corrGain\\K",
	"PositionControllerPan\\PID1\\kp",
	"PositionControllerPan\\PID1\\tauD",
	"PositionControllerPan\\PID1\\beta",
	"PositionControllerPan\\PID1\\tauI",
	"PositionControllerPan\\SignalLimiter2\\minimum",
	"PositionControllerPan\\SignalLimiter2\\maximum",
	"PositionControllerTilt\\corrGain\\K",
	"PositionControllerTilt\\PID1\\kp",
	"PositionControllerTilt\\PID1\\tauD",
	"PositionControllerTilt\\PID1\\beta",
	"PositionControllerTilt\\PID1\\tauI",
	"PositionControllerTilt\\SignalLimiter2\\minimum",
	"PositionControllerTilt\\SignalLimiter2\\maximum"
,	NULL
};
XXString xx_initial_value_names[] = {
	"PositionControllerPan\\PID1\\uD_previous_initial",
	"PositionControllerPan\\PID1\\error_previous_initial",
	"PositionControllerPan\\PID1\\uI_previous_initial",
	"PositionControllerTilt\\PID1\\uD_previous_initial",
	"PositionControllerTilt\\PID1\\error_previous_initial",
	"PositionControllerTilt\\PID1\\uI_previous_initial"
,	NULL
};
XXString xx_variable_names[] = {
	"PositionControllerPan\\corrGain\\corr",
	"PositionControllerPan\\PID1\\output",
	"",
	"PositionControllerPan\\SignalLimiter2\\output",
	"PositionControllerPan\\current_position",
	"PositionControllerPan\\target_position",
	"PositionControllerTilt\\corrGain\\output",
	"PositionControllerTilt\\PID1\\output",
	"",
	"PositionControllerTilt\\PlusMinus1\\output",
	"PositionControllerTilt\\SignalLimiter2\\output",
	"PositionControllerTilt\\current_position",
	"PositionControllerTilt\\target_position",
	"pitch_current_position",
	"pitch_target_position",
	"yaw_out",
	"pitch_out",
	"yaw_current_position",
	"yaw_target_position"
,	NULL
};
XXString xx_state_names[] = {
	"PositionControllerPan\\PID1\\uD_previous",
	"PositionControllerPan\\PID1\\error_previous",
	"PositionControllerPan\\PID1\\uI_previous",
	"PositionControllerTilt\\PID1\\uD_previous",
	"PositionControllerTilt\\PID1\\error_previous",
	"PositionControllerTilt\\PID1\\uI_previous"
,	NULL
};
XXString xx_rate_names[] = {
	"",
	"PositionControllerPan\\PID1\\error",
	"",
	"",
	"PositionControllerTilt\\PID1\\error",
	""
,	NULL
};
*/

#if (14 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void XXModelInitialize_parameters(void)
{
	/* set the parameters */
	xx_P[0] = 0.0;		/* PositionControllerPan\corrGain\K */
	xx_P[1] = 0.70;		/* PositionControllerPan\PID1\kp */
	xx_P[2] = 0.00;		/* PositionControllerPan\PID1\tauD */
	xx_P[3] = 0.17;		/* PositionControllerPan\PID1\beta */
	xx_P[4] = 0.5;		/* PositionControllerPan\PID1\tauI */
	xx_P[5] = -0.10;	/* PositionControllerPan\SignalLimiter2\minimum */
	xx_P[6] = 0.10;		/* PositionControllerPan\SignalLimiter2\maximum */

	xx_P[7] = 0.0;		/* PositionControllerTilt\corrGain\K */
	xx_P[8] = 0.5;		/* PositionControllerTilt\PID1\kp */
	xx_P[9] = 0.00;		/* PositionControllerTilt\PID1\tauD */
	xx_P[10] = 0.001;	/* PositionControllerTilt\PID1\beta */
	xx_P[11] = 0.5;		/* PositionControllerTilt\PID1\tauI */
	xx_P[12] = -0.10;	/* PositionControllerTilt\SignalLimiter2\minimum */
	xx_P[13] = 0.10;	/* PositionControllerTilt\SignalLimiter2\maximum */

}
#if (14 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void XXModelInitialize_initialvalues(void)
{
	/* set the initial values */
	xx_I[0] = 0.0;		/* PositionControllerPan\PID1\uD_previous_initial */
	xx_I[1] = 0.0;		/* PositionControllerPan\PID1\error_previous_initial */
	xx_I[2] = 0.0;		/* PositionControllerPan\PID1\uI_previous_initial */
	xx_I[3] = 0.0;		/* PositionControllerTilt\PID1\uD_previous_initial */
	xx_I[4] = 0.0;		/* PositionControllerTilt\PID1\error_previous_initial */
	xx_I[5] = 0.0;		/* PositionControllerTilt\PID1\uI_previous_initial */

}

void XXModelInitialize_states(void)
{
	/* set the states */
	xx_s[0] = xx_I[0];		/* PositionControllerPan\PID1\uD_previous */
	xx_s[1] = xx_I[1];		/* PositionControllerPan\PID1\error_previous */
	xx_s[2] = xx_I[2];		/* PositionControllerPan\PID1\uI_previous */
	xx_s[3] = xx_I[3];		/* PositionControllerTilt\PID1\uD_previous */
	xx_s[4] = xx_I[4];		/* PositionControllerTilt\PID1\error_previous */
	xx_s[5] = xx_I[5];		/* PositionControllerTilt\PID1\uI_previous */

}

void XXModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(xx_V, 0, xx_variables_size * sizeof(XXDouble));
}

/* this method is called before calculation is possible */
void XXModelInitialize (void)
{
	XXModelInitialize_parameters();
	XXModelInitialize_variables();
	XXModelInitialize_initialvalues();
	XXModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void XXCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	XXModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void XXCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void XXCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void XXCalculateDynamic (void)
{
	/* PositionControllerPan\PID1\factor = 1 / (sampletime + PositionControllerPan\PID1\tauD * PositionControllerPan\PID1\beta); */
	xx_V[2] = 1.0 / (xx_step_size + xx_P[2] * xx_P[3]);

	/* PositionControllerTilt\PID1\factor = 1 / (sampletime + PositionControllerTilt\PID1\tauD * PositionControllerTilt\PID1\beta); */
	xx_V[8] = 1.0 / (xx_step_size + xx_P[9] * xx_P[10]);

	/* PositionControllerTilt\current_position = pitch_current_position; */
	xx_V[11] = xx_V[13];

	/* PositionControllerTilt\target_position = pitch_target_position; */
	xx_V[12] = xx_V[14];

	/* PositionControllerPan\current_position = yaw_current_position; */
	xx_V[4] = xx_V[17];

	/* PositionControllerPan\target_position = yaw_target_position; */
	xx_V[5] = xx_V[18];

	/* PositionControllerTilt\PID1\error = PositionControllerTilt\target_position - PositionControllerTilt\current_position; */
	xx_R[4] = xx_V[12] - xx_V[11];

	/* PositionControllerPan\corrGain\corr = PositionControllerPan\corrGain\K * PositionControllerPan\current_position; */
	xx_V[0] = xx_P[0] * xx_V[4];

	/* PositionControllerPan\PID1\error = PositionControllerPan\target_position - PositionControllerPan\current_position; */
	xx_R[1] = xx_V[5] - xx_V[4];

	/* PositionControllerTilt\PID1\uD = PositionControllerTilt\PID1\factor * (((PositionControllerTilt\PID1\tauD * PositionControllerTilt\PID1\uD_previous) * PositionControllerTilt\PID1\beta + (PositionControllerTilt\PID1\tauD * PositionControllerTilt\PID1\kp) * (PositionControllerTilt\PID1\error - PositionControllerTilt\PID1\error_previous)) + (sampletime * PositionControllerTilt\PID1\kp) * PositionControllerTilt\PID1\error); */
	xx_R[3] = xx_V[8] * (((xx_P[9] * xx_s[3]) * xx_P[10] + (xx_P[9] * xx_P[8]) * (xx_R[4] - xx_s[4])) + (xx_step_size * xx_P[8]) * xx_R[4]);

	/* PositionControllerTilt\PID1\uI = PositionControllerTilt\PID1\uI_previous + (sampletime * PositionControllerTilt\PID1\uD) / PositionControllerTilt\PID1\tauI; */
	xx_R[5] = xx_s[5] + (xx_step_size * xx_R[3]) / xx_P[11];

	/* PositionControllerTilt\PID1\output = PositionControllerTilt\PID1\uI + PositionControllerTilt\PID1\uD; */
	xx_V[7] = xx_R[5] + xx_R[3];

	/* PositionControllerPan\PID1\uD = PositionControllerPan\PID1\factor * (((PositionControllerPan\PID1\tauD * PositionControllerPan\PID1\uD_previous) * PositionControllerPan\PID1\beta + (PositionControllerPan\PID1\tauD * PositionControllerPan\PID1\kp) * (PositionControllerPan\PID1\error - PositionControllerPan\PID1\error_previous)) + (sampletime * PositionControllerPan\PID1\kp) * PositionControllerPan\PID1\error); */
	xx_R[0] = xx_V[2] * (((xx_P[2] * xx_s[0]) * xx_P[3] + (xx_P[2] * xx_P[1]) * (xx_R[1] - xx_s[1])) + (xx_step_size * xx_P[1]) * xx_R[1]);

	/* PositionControllerPan\PID1\uI = PositionControllerPan\PID1\uI_previous + (sampletime * PositionControllerPan\PID1\uD) / PositionControllerPan\PID1\tauI; */
	xx_R[2] = xx_s[2] + (xx_step_size * xx_R[0]) / xx_P[4];

	/* PositionControllerPan\PID1\output = PositionControllerPan\PID1\uI + PositionControllerPan\PID1\uD; */
	xx_V[1] = xx_R[2] + xx_R[0];

	/* PositionControllerPan\SignalLimiter2\output = if PositionControllerPan\PID1\output < PositionControllerPan\SignalLimiter2\minimum... ; */
	xx_V[3] = ((xx_V[1] < xx_P[5]) ? 
		/* PositionControllerPan\SignalLimiter2\minimum */
		xx_P[5]
	:
		/* if PositionControllerPan\PID1\output > PositionControllerPan\SignalLimiter2\maximum...  */
		((xx_V[1] > xx_P[6]) ? 
			/* PositionControllerPan\SignalLimiter2\maximum */
			xx_P[6]
		:
			/* PositionControllerPan\PID1\output */
			xx_V[1]
		)
	);

	/* PositionControllerTilt\corrGain\output = PositionControllerTilt\corrGain\K * PositionControllerPan\corrGain\corr; */
	xx_V[6] = xx_P[7] * xx_V[0];

	/* PositionControllerTilt\PlusMinus1\output = PositionControllerTilt\corrGain\output + PositionControllerTilt\PID1\output; */
	xx_V[9] = xx_V[6] + xx_V[7];

	/* PositionControllerTilt\SignalLimiter2\output = if PositionControllerTilt\PlusMinus1\output < PositionControllerTilt\SignalLimiter2\minimum... ; */
	xx_V[10] = ((xx_V[9] < xx_P[12]) ? 
		/* PositionControllerTilt\SignalLimiter2\minimum */
		xx_P[12]
	:
		/* if PositionControllerTilt\PlusMinus1\output > PositionControllerTilt\SignalLimiter2\maximum...  */
		((xx_V[9] > xx_P[13]) ? 
			/* PositionControllerTilt\SignalLimiter2\maximum */
			xx_P[13]
		:
			/* PositionControllerTilt\PlusMinus1\output */
			xx_V[9]
		)
	);


	/* increment the step counter */
	xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void XXCalculateOutput (void)
{
	/* yaw_out = PositionControllerPan\SignalLimiter2\output; */
	xx_V[15] = xx_V[3];

	/* pitch_out = PositionControllerTilt\SignalLimiter2\output; */
	xx_V[16] = xx_V[10];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void XXCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void XXModelTerminate(void)
{
}

